apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source: 
  repoURL: https://github.com/satyamuralidhar/argocd.git
  targetRevision: HEAD
  path: argo
destination: 
  server: https://kubenetes.default.svc
  namespace: satya
syncPolicy:
  syncOptions:
  - CreatedNamespace: true
automated:
  selfHeal: true
  prune: true #it will delete manual changes
